[package]
name = "rustdotenv"
version = "0.1.0"
authors = ["Misrab <faizullah.misrab@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"